config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :markets, only: [:index, :show]
  resources :vendors, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  def index
    @markets = MarketApiHelper.fetch_markets
  end

  def show
    @market = MarketApiHelper.fetch_market(params[:id])
    @vendors = MarketApiHelper.fetch_vendors(params[:id])
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def show
    @vendor = VendorApiHelper.fetch_vendor(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/market_api_helper.rb
require 'httparty'

module MarketApiHelper
  include HTTParty
  base_uri 'http://localhost:3000'

  def self.fetch_markets
    response = get('/api/v0/markets')

    if response.success?
      parse_markets_response(response)
    else
      nil 
    end
  end

  def self.fetch_market(id)
    response = get("/api/v0/markets/#{id}")
    
    if response.success?
      parse_markets_response(response)
    else
      nil
    end
  end

  def self.fetch_vendors(id)
    response = get("/api/v0/markets/#{id}/vendors")

    if response.success?
      parse_markets_response(response)
    else
      nil
    end
  end

  private

  def self.parse_markets_response(response)
    data = JSON.parse(response.body)
    markets_data = data['data']
    markets_data
  end
end

app/helpers/vendor_api_helper.rb
require "httparty"

module VendorApiHelper
  include HTTParty
  base_uri 'http://localhost:3000'
  
  def self.fetch_vendor(id)
    response = get("/api/v0/vendors/#{id}")
    
    if response.success?
      parse_vendors_response(response)
    else
      nil
    end
  end
  
  def self.parse_vendors_response(response)
    data = JSON.parse(response.body)
    vendors_data = data['data']
    vendors_data
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketMoneyFe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/markets/index.html.erb
<h1 class="text-center">Markets</h1>

<table class="markets-table">
  <thead>
    <tr>
      <th class="text-center">Name</th>
      <th class="text-center">City</th>
      <th class="text-center">State</th>
      <th class="text-center">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @markets.each_with_index do |market, index| %>
      <tr class="market-row <%= index.even? ? 'even-row' : 'odd-row' %>">
        <td><%= market["attributes"]["name"] %></td>
        <td><%= market["attributes"]["city"] %></td>
        <td><%= market["attributes"]["state"] %></td>
        <td>
          <%= form_tag market_path(market["id"]), method: :get do %>
            <%= submit_tag 'More Info', class: 'more-info-button' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/markets/show.html.erb
<div class="centered-content">
<h1><%= @market["attributes"]["name"] %></h1>
<%= @market["attributes"]["street"] %>
<br>
<%= @market["attributes"]["city"] %>, <%= @market["attributes"]["state"] %> <%= @market["attributes"]["zip"] %>
</div>

<h4>Vendors at our Market:</h4>
<ul>
  <% @vendors.each do |vendor| %>
    <li>
      <%= link_to vendor["attributes"]["name"], vendor_path(vendor["id"]) %>
    </li>
  <% end %>
</ul>

app/views/vendors/show.html.erb
<div class="centered-content">
  <h1><%= @vendor["attributes"]["name"] %></h1>
</div>
  Contact Info:<br>
  Name: <%= @vendor["attributes"]["contact_name"] %><br>
  Phone: <%= @vendor["attributes"]["contact_phone"] %><br>
  <p>Credit Accepted?: <%= @vendor["attributes"]["accept_credit"] ? 'YES' : 'NO' %></p>
  <p>Description: <%= @vendor["attributes"]["description"] %></p>